# N scan script (auto-generated by diagnose_round19.py)
$n_values = @(200, 400, 600, 800, 1000)
$gamma = 6.0
$beta = 0.6
$grid_res = 40
$duration = 2.0

foreach ($n in $n_values) {
    Write-Host "Running N=$n..."
    $env:SIM_GAMMA = $gamma
    $env:SIM_BETA = $beta
    $env:SIM_N_SATS = $n
    $env:SIM_GRID_RES = $grid_res
    $env:SIM_DURATION = $duration
    $env:SIM_OUTPUT_PHI = 0
    
    ./multilayer_sim_real.exe
    
    $output_name = "multilayer_results_N_$n.json"
    if (Test-Path multilayer_results_real.json) {
        Move-Item multilayer_results_real.json $output_name -Force
    }
    
    Write-Host "N=$n done."
}

Write-Host "N scan complete."
