# Gamma scan script (auto-generated by diagnose_round19.py)
$gamma_values = @(0.1, 0.3, 0.5, 0.8, 1.0, 1.5, 3.0, 6.0, 10.0)
$beta = 0.6
$n_sats = 1000
$grid_res = 40
$duration = 2.0

foreach ($gamma in $gamma_values) {
    Write-Host "Running gamma=$gamma..."
    $env:SIM_GAMMA = $gamma
    $env:SIM_BETA = $beta
    $env:SIM_N_SATS = $n_sats
    $env:SIM_GRID_RES = $grid_res
    $env:SIM_DURATION = $duration
    $env:SIM_OUTPUT_PHI = 0
    
    ./multilayer_sim_real.exe
    
    # Rename output
    $output_name = "multilayer_results_gamma_$gamma.json"
    if (Test-Path multilayer_results_real.json) {
        Move-Item multilayer_results_real.json $output_name -Force
    }
    
    Write-Host "gamma=$gamma done."
}

Write-Host "Gamma scan complete."
