# Gamma critical scan script (auto-generated by diagnose_round19.py)
$gamma_values = @(0.35, 0.40, 0.44, 0.45, 0.48, 0.50, 0.55, 0.60, 0.70)
$beta = 0.6
$n_sats = 1000
$grid_res = 40
$duration = 2.0

foreach ($gamma in $gamma_values) {
    Write-Host "Running gamma=$gamma (near critical)..."
    $env:SIM_GAMMA = $gamma
    $env:SIM_BETA = $beta
    $env:SIM_N_SATS = $n_sats
    $env:SIM_GRID_RES = $grid_res
    $env:SIM_DURATION = $duration
    $env:SIM_OUTPUT_PHI = 0
    
    ./multilayer_sim_real.exe
    
    $output_name = "multilayer_results_gamma_critical_$gamma.json"
    if (Test-Path multilayer_results_real.json) {
        Move-Item multilayer_results_real.json $output_name -Force
    }
    
    Write-Host "gamma=$gamma done."
}

Write-Host "Gamma critical scan complete."
