"""
===============================================================================
Real-time Sweep Analysis: Theory-vs-Simulation Comparison
===============================================================================

Reads sweep results as they are generated by run_sweeps.py and:
1. Fits N-scaling exponent alpha (n_cores ∝ N^α)
2. Fits gamma-scaling (n_cores vs gamma)
3. Compares with theoretical predictions from dim2/dim4/dim5
4. Prepares data collapse validation
5. Per-layer core count analysis (cross-layer coupling)

Usage: python analyze_sweeps.py
Rerun any time to pick up latest sweep data.
===============================================================================
"""

import json, sys, io, os, glob
import numpy as np
from scipy.stats import linregress
from scipy.optimize import curve_fit
import warnings
warnings.filterwarnings('ignore')

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

RESULTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "results")

print("=" * 70)
print("Real-time Sweep Analysis: Theory vs Simulation")
print("=" * 70)

# =====================================================================
# Part 1: N-Scaling Analysis (n_cores vs N)
# =====================================================================

print("\n" + "=" * 70)
print("Part 1: N-Scaling (n_cores vs N) — Round 15: n_cores INDEPENDENT of N")
print("=" * 70)

n_scaling_path = os.path.join(RESULTS_DIR, "n_scaling_summary.json")
if os.path.exists(n_scaling_path):
    with open(n_scaling_path) as f:
        n_data = json.load(f)
    
    N_vals = np.array([d["N"] for d in n_data])
    n_cores_vals = np.array([d["avg_cores"] for d in n_data])
    
    # Power law fit: n_cores = A * N^alpha
    log_N = np.log(N_vals)
    log_n = np.log(n_cores_vals)
    slope, intercept, r_val, p_val, std_err = linregress(log_N, log_n)
    alpha_fitted = slope
    A_fitted = np.exp(intercept)
    
    print(f"\n  Data points: {len(N_vals)}")
    print(f"  {'N':>8s}  {'n_cores':>10s}")
    print(f"  {'-'*8}  {'-'*10}")
    for N, n in zip(N_vals, n_cores_vals):
        print(f"  {N:8d}  {n:10.3f}")
    
    print(f"\n  Power law fit: n_cores = {A_fitted:.3f} * N^{alpha_fitted:.4f}")
    print(f"  R² = {r_val**2:.6f}")
    print(f"  alpha (fitted)  = {alpha_fitted:.4f} ± {std_err:.4f}")
    
    # CRITICAL (Round 16): ALL sweep data is SYNTHETIC from saturation model.
    # Model overpredicts by 35% at gamma=6.0 (123.1 vs C++ 92.3).
    # CRITICAL (Round 15): n_cores is INDEPENDENT of N.
    # C++ evidence: n_cores ≈ 92.3 for both N=400 and N=1000.
    print(f"\n  Round 15+16: ALL data is SYNTHETIC (saturation model).")
    print(f"  n_cores is INDEPENDENT of N (alpha ≈ 0).")
    print(f"  C++ validated: n_cores ≈ 92.3 at gamma=6.0 for both N=400 and N=1000")
    print(f"  WARNING: Model predicts 123.1 (35% overestimate) at gamma=6.0")
    print(f"  Data source: SYNTHETIC (saturation model, DOES NOT MATCH C++ DATA)")
    
    n_analysis = {
        "N": N_vals.tolist(),
        "n_cores": n_cores_vals.tolist(),
        "alpha_fitted": float(alpha_fitted),
        "alpha_std_err": float(std_err),
        "R2": float(r_val**2),
        "A_fitted": float(A_fitted),
        "note": "Round 15: n_cores independent of N. C++ validated only at gamma=6.0.",
    }
else:
    print("\n  [WAITING] n_scaling_summary.json not yet available")
    n_analysis = None

# =====================================================================
# Part 2: Gamma Scan Analysis
# =====================================================================

print("\n" + "=" * 70)
print("Part 2: Gamma Scan (n_cores vs chemotactic strength)")
print("=" * 70)

gamma_path = os.path.join(RESULTS_DIR, "gamma_scan_summary.json")
if os.path.exists(gamma_path):
    with open(gamma_path) as f:
        g_data = json.load(f)
    
    gammas = np.array([d["gamma"] for d in g_data])
    n_cores_g = np.array([d["avg_cores"] for d in g_data])
    
    print(f"\n  Data points: {len(gammas)}")
    print(f"  {'γ':>8s}  {'n_cores':>10s}")
    print(f"  {'-'*8}  {'-'*10}")
    for g, n in zip(gammas, n_cores_g):
        print(f"  {g:8.1f}  {n:10.3f}")
    
    # Theory: gamma_c = (16+β)/37.38 ≈ 0.4441 for β=0.6 (nonlocal KS)
    # For gamma >> gamma_c, n_cores ~ constant (saturation)
    # For gamma just above gamma_c, n_cores ~ m * ln(gamma/gamma_c) or power law
    
    gamma_c_theory = (16.0 + 0.6) / 37.38  # = 0.4441 (nonlocal KS)
    
    # Fit n_cores vs log(gamma) for gamma > gamma_c
    mask_super = gammas > gamma_c_theory
    if np.sum(mask_super) >= 3:
        log_g = np.log(gammas[mask_super] - gamma_c_theory)
        log_n_g = np.log(n_cores_g[mask_super])
        slope_g, _, r_g, _, _ = linregress(log_g, log_n_g)
        print(f"\n  Near critical (γ > γ_c):")
        print(f"    n_cores ∝ (γ - γ_c)^({slope_g:.4f})")
        print(f"    R² = {r_g**2:.6f}")
    
    # Simple log-log fit for all data
    log_g_all = np.log(gammas)
    log_n_all = np.log(n_cores_g)
    slope_all, _, r_all, _, _ = linregress(log_g_all, log_n_all)
    print(f"\n  Global power law: n_cores ∝ γ^({slope_all:.4f})")
    print(f"    R² = {r_all**2:.6f}")
    
    gamma_analysis = {
        "gamma_values": gammas.tolist(),
        "n_cores": n_cores_g.tolist(),
        "gamma_c_theory": gamma_c_theory,
        "global_exponent": float(slope_all),
        "global_R2": float(r_all**2),
    }
else:
    print("\n  [WAITING] gamma_scan_summary.json not yet available")
    gamma_analysis = None

# =====================================================================
# Part 3: Theory-vs-Simulation Comparison Table
# =====================================================================

print("\n" + "=" * 70)
print("Part 3: Theory-vs-Simulation Consolidated")
print("=" * 70)

print(f"""
{'Quantity':<35s} {'Theory':>12s} {'Simulation':>12s} {'Match':>8s}
{'-'*35} {'-'*12} {'-'*12} {'-'*8}""")

comparisons = []

# From dim4 theory:
# n_cores(N=1000, gamma=6, beta=0.6) ≈ 102.5 (linear), ~191 for 3D grid effects

# N-scaling alpha
if n_analysis:
    # CRITICAL (Round 16): alpha=0 (n_cores independent of N). C++ validated.
    print(f"{'α (core count exponent)':<35s} {'0.0 (Round 15)':>12s} {alpha_fitted:>12.4f} {'△':>8s}")
    print(f"  NOTE: Fitted alpha from synthetic data; C++ shows n_cores≈92.3 for all N.")

# gamma scan: core count saturation
# CRITICAL (Round 16): Model predicts 123.1 at gamma=6.0, C++ shows 92.3 (35% lower)
print(f"{'n_cores at N=400, γ=6':<35s} {'123.1 (model)':>12s} {'92.3 (C++)':>12s} {'✗':>8s}")
print(f"  WARNING: Model overestimates by 35%. Synthetic data uses 123.1.")

# Core count at default params
if n_analysis and len(N_vals) >= 6:
    n1000_sim = n_cores_vals[-1]
    # CRITICAL (Round 16): Model predicts 123.1; C++ shows 92.3
    print(f"{'n_cores at N=1000':<35s} {'123.1 (model)':>12s} {n1000_sim:>12.1f} {'✗':>8s}")
    print(f"  C++ validated: n_cores ≈ 92.3 at gamma=6.0 (independent of N)")
    print(f"  Model overestimates by 35% (123.1 vs 92.3)")

# =====================================================================
# Part 4: Per-Layer Core Count Analysis (Cross-Layer Coupling)
# =====================================================================

print("\n" + "=" * 70)
print("Part 4: Cross-Layer Coupling Analysis")
print("=" * 70)

# Read detailed results for N=1000 to analyze per-layer cores
detail_file = os.path.join(RESULTS_DIR, "n_scaling_gamma6.0_beta0.6_N1000.json")
if os.path.exists(detail_file):
    with open(detail_file) as f:
        detail = json.load(f)
    
    final_cores = detail.get("final_cores", {})
    x_layers = final_cores.get("x", [])
    y_layers = final_cores.get("y", [])
    z_layers = final_cores.get("z", [])
    
    n_layers = len(x_layers)
    print(f"\n  Layer structure: {n_layers} layers detected")
    
    layer_counts = []
    for i in range(n_layers):
        n_cores_layer = len(x_layers[i])
        layer_counts.append(n_cores_layer)
        
        if n_cores_layer > 0:
            x_arr = np.array(x_layers[i])
            y_arr = np.array(y_layers[i]) if i < len(y_layers) else np.zeros_like(x_arr)
            z_arr = np.array(z_layers[i]) if i < len(z_layers) else np.zeros_like(x_arr)
            
            centroid = np.array([np.mean(x_arr), np.mean(y_arr), np.mean(z_arr)])
            r_distances = np.sqrt(x_arr**2 + y_arr**2 + z_arr**2)
            mean_r = np.mean(r_distances)
            std_r = np.std(r_distances)
            
            print(f"    Layer {i+1}: {n_cores_layer:4d} cores, "
                  f"centroid=({centroid[0]:.1f},{centroid[1]:.1f},{centroid[2]:.1f}), "
                  f"mean_r={mean_r:.2f}±{std_r:.2f}")
    
    print(f"\n  Total cores: {sum(layer_counts)} (avg {n_cores_vals[-1]:.1f})")
    print(f"  Per-layer distribution: {layer_counts}")
    
    # Cross-layer coupling metrics
    if n_layers >= 2:
        # Layer separation analysis
        for i in range(n_layers):
            for j in range(i+1, min(i+2, n_layers)):
                if layer_counts[i] > 0 and layer_counts[j] > 0:
                    # Find nearest core distances between layers
                    xi, yi, zi = np.array(x_layers[i]), np.array(y_layers[i]), np.array(z_layers[i])
                    xj, yj, zj = np.array(x_layers[j]), np.array(y_layers[j]), np.array(z_layers[j])
                    
                    # Approximate inter-layer core distance
                    centroid_i = np.array([np.mean(xi), np.mean(yi), np.mean(zi)])
                    centroid_j = np.array([np.mean(xj), np.mean(yj), np.mean(zj)])
                    centroid_dist = np.linalg.norm(centroid_i - centroid_j)
                    
                    print(f"    L{i+1}↔L{j+1} centroid distance: {centroid_dist:.2f}")
    
    # Save per-layer analysis
    layer_analysis = {
        "n_layers": n_layers,
        "layer_core_counts": layer_counts,
        "total_cores": sum(layer_counts),
    }
else:
    print("\n  [WAITING] Detailed N=1000 results not yet available")
    layer_analysis = None

# =====================================================================
# Part 5: Data Collapse Methodology (Prepared for Phase Diagram)
# =====================================================================

print("\n" + "=" * 70)
print("Part 5: Data Collapse Preparation")
print("=" * 70)

print("""
Data collapse is the definitive test of universality class.
Once the full phase_diagram sweep completes from actual C++ data:

1. For each (gamma, beta, N) triplet, compute:
   - Scaled core count: n_cores (absolute, independent of N)
   - Scaling variable: ε where ε = sqrt((γ-γ_c)/γ_c)

2. If mean-field universality holds, ALL points collapse to:
   n_cores = Φ(ε)
   where Φ is a universal scaling function.

3. Quality of collapse: quantified by the spread of Φ values
   - Perfect collapse: σ(Φ) / μ(Φ) < 0.05
   - Good collapse: σ/μ < 0.10
   - Poor collapse: σ/μ > 0.20 (wrong universality class or exponents)

CRITICAL (Round 16): Current data is SYNTHETIC. Real C++ data needed.
Expected result: n_cores ≈ 92.3 at gamma=6.0 (C++ validated).
""")

# =====================================================================
# Part 6: Phase Diagram Cross-Section (from sweep data)
# =====================================================================

print("=" * 70)
print("Part 6: Phase Diagram Preliminary")
print("=" * 70)

if n_analysis:
    # Use the N-scaling data to infer phase boundaries
    # At gamma=6.0, beta=0.6: all N ≥ 100 show core formation (ordered phase)
    # This confirms dim5 prediction: gamma=6 >> gamma_c=1.89 → deep ordering
    
    # Estimate phase boundaries from core counts
    n_cores_per_sat = n_cores_vals / N_vals
    print(f"\n  Core efficiency (n_cores / N) vs N:")
    for N, eff in zip(N_vals, n_cores_per_sat):
        phase_label = "Deep" if eff > 0.5 else ("Strong" if eff > 0.2 else "Weak")
        print(f"    N={N:4d}: {eff:.4f} cores/sat  [{phase_label} ordering]")
    
    print(f"\n  At γ=6.0, β=0.6: firm deep ordering phase for all N tested.")
    print(f"  This matches dim5 prediction: γ/γ_c = {6.0/((16.0+0.6)/37.38):.1f} >> 1")
else:
    print("\n  [WAITING] Need completed N-scaling data for phase analysis")

# =====================================================================
# Save Analysis Report
# =====================================================================

output = {
    "analysis_version": "1.0",
    "timestamp": str(np.datetime64('now')),
    "n_scaling": n_analysis,
    "gamma_scan": gamma_analysis,
    "layer_analysis": layer_analysis,
    "theoretical_reference": {
        "gamma_c (beta=0.6)": 0.4441,
        "k_c (default)": 3.2774,
        "lambda_c (default)": 1.92,
        "alpha_n_cores": 0.0,
        "note": "Round 16: n_cores independent of N (alpha=0). Saturation model UNVALIDATED.",
        "universality_class": "mean-field",
        "critical_line": "(16+β)/37.38 (nonlocal KS)",
        "c++_validated": "n_cores ≈ 92.3 at gamma=6.0, beta=0.6",
        "model_overestimate": "123.1 (35% above C++)",
    },
}

report_path = os.path.join(RESULTS_DIR, "analysis_report.json")
with open(report_path, 'w', encoding='utf-8') as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"\n{'='*70}")
print(f"Analysis report saved: {report_path}")
print(f"{'='*70}")

# =====================================================================
# Key Findings Summary
# =====================================================================

print("""
=== KEY FINDINGS (Round 16 corrected) ===

1. N-scaling: n_cores is INDEPENDENT of N (alpha = 0).
   C++ validated: n_cores ≈ 92.3 for both N=400 and N=1000.
   The saturation model predicts 123.1 (35% overestimate) — DO NOT USE.

2. Gamma scan: Core count from synthetic saturation model.
   Model predicts 91.6 (gamma=0) → 123.1 (gamma=6.0), but C++ shows 92.3.
   The saturation model is FUNDAMENTALLY UNVALIDATED.

3. Cross-layer coupling: Per-layer core distribution from synthetic data.
   All values are model predictions, not C++ data.

4. Phase diagram: Default params (gamma=6, beta=0.6) are deep in the ordered phase,
   but the quantitative core count prediction is wrong (123.1 vs 92.3).

5. ALL synthetic data files need to be regenerated from actual C++ simulations.
   Current data is self-consistent with the model but does NOT match reality.
""")